// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbwxgkhfkgprjbkalsgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFid3hna2hma2dwcmpia2Fsc2duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjc1NDUsImV4cCI6MjA3MTk0MzU0NX0.xlSDcREuaFQ1ET1gswSRFfrIhjy0vodNea_u3byCRss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});